# Gemini API
GEMINI_API_KEY = "AIzaSyABmn_9JyQFGvtK10VRlrwofoRHEc4y6RM"

# Firebase service account in TOML table format
[firebase_service_account]
type = "service_account"
project_id = "chatbot0x007b"
private_key_id = "e74459034b63a1751c64ffd14a120b1f08316d5a"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDXHKIvp8ngheI5
FGCvburfhhHQbNEbK2clAl4yfDGZaX5EAmVZEf1nnNJ4WzCj+CB8skrCTcmNFdld
greJ3dwo9hYle8Lhe4GLHtvmgST7Q5vXHqj/iH/XcoeZHfWJLXq7w7vPGZyz37Ii
uow6jyaJztVzLOKhopLlJ3sAlwjSmhLqO+VxV4Scy0YDXZNdY+TlwzNQ5FJLyNYX
RWUH+f1Qa8x37PTJDg1Mq7XLtvZEQO41C02HvX6luK4lUOXF+/wHr00mcHbuxb4z
m5x4iXl/9UzfcBfNppjIunc1QRXGziYr5SWULfcRVh5zAKAbIGcQrVpXPCXsa0Cf
uGm7DUzRAgMBAAECggEAArlmu7iFFwI1dE0nI887BRlp/cqEM+yohEVLrnM+8nWa
iLxoiB7qx2s3oz7rABqaRVLOalGvbKL2Rm5FClQpIuSQV3yiCINZ4SpWNQzVf3A5
FIzh4KzIsX1uc1b+XYfaF7xoLM/JcztqvCPPA8aKFNSN6x6QuktB9b1UInsaYuz6
/y0xEByONlKvAPrUwo0zAM6i61CFYzeUeQX4uuwwDYT0gROYf6lOZA8csjs5lFXw
2HVqt1GiNisNoao8FmnTU1CIT30xq6cZeBD/EVUEY7C6x/keP6NX6tsyxStAZ5YL
+YjqFjN9tsHTuRgHZYAV1Z0ERpMZHbAnb8t2Yf5QOQKBgQD0i4vnC8KMfQY8QKWU
lX41oYsfBgJ6HKAN/ykDfIjOr0NCYPKN7E2NwPpabEdFnA8XnZ4Stl8wj9IQOONS
0WO67Kx+klE0y0IcpenWjOXGwNNKY0gj9wBCte/WqyhvjGxS55tDttkrFkrRBPtl
ZE1KqoXusmPW6I1yR2/7KLCbmQKBgQDhMCOnyPbaoM7gfJ86/I+er4mN14cLwHgX
2UxVy3gpGTelVrHdGBRXDs2lsbT6fL6GX5RJU6egwWP9yiugzhzJu8DsafDtYSxp
fy1s1VYCnZlmwFJ651yzk/hmTNE+xbiIb7p7AHJVUrrGK8oWoAFnvJZLMNEYEAFU
vdaL11a9+QKBgQDn9YXavpjnUaAcfuWQrsxsarLf1n96/LQFEscAe5v5EN2nlPX+
EOrvTuEp7BMewAzAxc0uyrY4BfOnV46o+9yxbdWgqYFFppcrPWU1EajSggzpPosr
MhuZK6I36VoNlREbAn2QGVydNiP5Z9ReNGnsLRulcqipLSUeBQz/G3WJ4QKBgQDT
OVVoj5/FKSuD9EFjkf2hSmRLUQwSYOIE9MWegDFg04+Xnf9ONMT3eCI7trncb2BD
KKouMbK9nkkNiDJuLodgTqXC3AiqkQiYmDtip6V65Js8f0+eiyAwLa7FPm7TY6EZ
ETwpHh0gnW4mbnKr0EAhLwsG0m5/FJw7AaqaF038+QKBgAhEpf1PY1nRpWIiNDcX
Xy9O/ajveh2m0rU6tjc8Dh1G1kkF/lWHOAtoWhwXcEDlYF0AQQGBsLRwC454d5BC
VdXuZ/TqdA3g6E1apHcRpSko3Y2Mr3xeWoJEWxAqrVWcl6CVWtY/PmgIpV0wDq4z
Ik2OeaIsiK2p0lhFN/C0xPUM
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@chatbot0x007b.iam.gserviceaccount.com"
client_id = "108010087438947550188"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40chatbot0x007b.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
